version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend-network

  # main Service
  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: invoice-service
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/invoice
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend-network

  # Email Sending Service
  email-sender:
    build:
      context: ./email-sender
      dockerfile: Dockerfile
    container_name: email-sender
    restart: always
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    networks:
      - backend-network

volumes:
  mongo-data:
    driver: local

networks:
  backend-network:
    driver: bridge
